apiVersion: v1
kind: Service
metadata:
  labels:
    app: concept-candidates
  name: concept-candidates
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    app: concept-candidates
status:
  loadBalancer: {}
